# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Word.create!(english: "explain", german: "erklären")

vocab_arrow = [["word", "Wort"],
["said", "gesagt"],
["there", "da"],
["use", "benutzen/nutzen"],
["will", "werden"],
["other", "anderer"],
["many", "viele"],
["some", "einige"],
["would", "würde"],
["make", "machen/krieren"],
["like", "mögen"],
["him", "Ihn"],
["into", "hinein"],
["time", "die Zeit"],
["look", "gucken"],
["more", "mehr"],
["write", "schreiben"],
["number", "die Nummer/Zahl"],
["way", "der Weg"],
["could", "könnte"],
["people", "die Leute"],
["call", "der Anruf"],
["oil", "das Öl"],
["now", "nun/jetzt"],
["find", "finden"],
["long", "lang"],
["down", "unten"],
["day", "der Tag"],
["get", "bekommen/kriegen"],
["may", "der Mai"],
["part", "der Teil"],
["over", "über"],
["sound", "der Klang"],
["take", "nehmen"],
["only", "nur/einzig"],
["little", "klein"],
["work", "die Arbeit"],
["know", "wissen"],
["place", "der Platz/Ort"],
["year", "das Jahr"],
["give", "geben"],
["very", "besonders"],
["after", "danach/nach"],
["thing", "die Sache"],
["our", "unser"],
["name", "der Name"],
["sentence", "der Satz"],
["think", "denken"],
["say", "sagen"],
["where", "wo"],
["help", "helfen/Hilfe"],
["through", "durch"],
["much", "viel"],
["before", "vor"],
["line", "die Linie"],
["right", "korrekt/rechts"],
["too", "auch"],
["mean", "meinen"],
["tell", "sagen"],
["boy", "der Junge"],
["follow", "folgen"],
["came", "kam"],
["show", "zeigen"],
["form", "die Form"],
["small", "klein"],
["put", "stellen"],
["another", "anderer"],
["must", "müssen"],
["even", "eben/ausgeglichen"],
["because", "weil"],
["turn", "umdrehen"],
["here", "hier"],
["why", "warum"],
["ask", "fragen"],
["went", "kam"],
["men", "die Männer"],
["read", "lesen"],
["need", "brauchen"],
["land", "das Land"],
["different", "anders"],
["home", "das Zuhause"],
["move", "bewegen"],
["try", "versuchen"],
["kind", "freundlich"],
["hand", "die Hand"],
["picture", "das Bild"],
["again", "wieder/nochmal"],
["change", "ändern"],
["play", "spielen"],
["spell", "buchstabieren"],
["air", "die Luft"],
["away", "weg"],
["animal", "das Tier"],
["house", "das Haus"],
["point", "der Punkt"],
["page", "die Seite"],
["letter", "der Brief"],
["mother", "die Mutter"],
["answer", "die Antwort"],
["found", "gefunden"],
["study", "studieren/lernen"],
["still", "immernoch"],
["learn", "lernen"],
["world", "die Welt"],
["high", "hoch"],
["every", "jeder"],
["near", "nahe"],
["add", "hinzufügen/addieren"],
["food", "das Essen"],
["between", "zwischen"],
["own", "eigen"],
["below", "unter"],
["country", "das Land"],
["plant", "die Pflanze"],
["last", "letzter"],
["school", "die Schule"],
["father", "der Vater"],
["keep", "behalten"],
["tree", "der Baum"],
["never", "niemals"],
["start", "der Start"],
["city", "die Stadt"],
["earth", "die Erde"],
["eye", "das Auge"],
["light", "das Licht"],
["thought", "der Gedanke"],
["head", "der Kopf"],
["under", "unter"],
["story", "die Geschichte"],
["saw", "sah"],
["left", "links"],
["few", "einige"],
["while", "während"],
["along", "entlang"],
["might", "gegebenenfalls"],
["close", "nahe"],
["something", "etwas"],
["seem", "scheinen"],
["next", "nächster/nächstes"],
["hard", "schwer"],
["open", "offen"],
["example", "das Beispiel"],
["begin", "anfangen"],
["life", "das Leben"],
["always", "immer"],
["those", "diese/jene"],
["both", "beide"],
["paper", "das Papier"],
["together", "zusammen"],
["group", "die Gruppe"],
["often", "oft"],
["run", "rennen"],
["important", "wichtig"],
["until", "bis"],
["children", "die Kinder"],
["feet", "die Füße"],
["car", "das Auto"],
["night", "die Nacht"],
["walk", "gehen"],
["white", "weiß"],
["sea", "das Meer"],
["began", "anfing"],
["grow", "wachsen"],
["took", "nahm"],
["river", "der Fluss"],
["carry", "tragen"],
["state", "der Staat"],
["once", "einmal"],
["book", "das Buch"],
["hear", "hören"],
["stop", "stoppen"],
["without", "ohne"],
["second", "zweiter"],
["later", "später"],
["miss", "fehlen"],
["idea", "die Idee"],
["enough", "genug"],
["eat", "essen"],
["face", "das Gesicht"],
["watch", "schauen"],
["far", "weit"],
["really", "wirklich"],
["almost", "fast"],
["let", "lassen"],
["above", "über"],
["girl", "das Mädchen"],
["sometimes", "ab und zu"],
["mountain", "der Berg"],
["young", "jung"],
["talk", "sprechen"],
["soon", "bald"],
["list", "die Liste"],
["being", "sein"],
["leave", "verlassen"],
["body", "der Körper"],
["stand", "stehen"],
["questions", "die Fragen"],
["fish", "der Fisch"],
["area", "die Gegend/Fläche"],
["mark", "das Mal/ der Fleck"],
["dog", "der Hund"],
["horse", "das Pferd"],
["birds", "die Vögel"],
["problem", "das Problem"],
["complete", "komplett"],
["room", "der Raum"],
["knew", "wissen"],
["since", "seit"],
["ever", "jemals"],
["piece", "das Stück/ der Teil"],
["usually", "normalerweise"],
["friends", "der Freund"],
["heard", "gehört"],
["order", "die Ordnung"],
["door", "die Tür"],
["sure", "sicher"],
["become", "bekam"],
["ship", "das Schiff"],
["across", "darüber/herüber"],
["today", "heute"],
["during", "während"],
["however", "wie auch immer"],
["low", "niedrig"],
["hours", "die Stunden"],
["happened", "passiert"],
["whole", "ganz/gesamt"],
["measure", "messen"],
["remember", "erinnern"],
["early", "früh"],
["waves", "die Wellen"],
["reached", "erreichen"],
["listen", "zuhören"],
["space", "der Platz"],
["covered", "bedeckt"],
["fast", "schnell"],
["several", "einige"],
["hold", "gehalten"],
["toward", "entgegen"],
["step", "der Schritt"],
["passed", "bestanden"],
["against", "gegen"],
["pattern", "das Muster"],
["table", "der Tisch"],
["slowly", "langsam"],
["map", "die Karte/Mappe"],
["farm", "die Farm"],
["pulled", "gezogen"],
["draw", "zeichnen"],
["voice", "die Stimme"],
["seen", "gesehen"],
["cold", "kalt"],
["cried", "geweint"],
["plan", "der Plan"],
["notice", "zur Kenntnis nehmen"],
["sing", "singen"],
["war", "der Krieg"],
["ground", "der Boden/ die Erde"],
["fall", "scheitern"],
["king", "der König"],
["town", "die Stadt"],
["unit", "die Einheit"],
["figure", "die Figur"],
["certain", "sicher"],
["field", "das Feld"],
["travel", "reisen"],
["wood", "das Holz"],
["fire", "das Feuer"],
["done", "getan"],
["road", "die Straße"],
["halt", "der Halt/Aufenthalt"],
["fly", "fliegen"],
["gave", "gab"],
["box", "der Kasten/Karton"],
["finally", "endlich"],
["wait", "warten"],
["correct", "korrekt"],
["quickly", "schnell/fix"],
["person", "die Person"],
["became", "werden/bekommen"],
["shown", "gezeigt"],
["front", "Die Vorderseite/Front"],
["feel", "fühlen"],
["fact", "der Fakt"],
["street", "die Straße"],
["decided", "entschieden"],
["contain", "beinhalten"],
["course", "der Kurs/ die Richtung"],
["surface", "die Oberfläche"],
["produce", "produzieren"],
["building", "das Gebäude"],
["ocean", "das Meer"],
["class", "die Klasse"],
["note", "die Notiz"],
["nothing", "nichts"],
["rest", "der Rest"],
["carefully", "vorsichtig"],
["scientist", "der Wissenschaftler"],
["inside", "in/drinne"],
["wheels", "die Räder"],
["stay", "bleiben"],
["known", "bekannt"],
["island", "die Insel"],
["less", "weniger"],
["machine", "die Maschiene"],
["base", "die Basis/Grundlage"],
["ago", "vor (3 Jahren...)"],
["stood", "stand"],
["plane", "das Flugzeug"],
["system", "das System"],
["behind", "hinter"],
["ran", "rannte"],
["round", "rund"],
["boat", "das Boot"],
["game", "das Spiel"],
["force", "die Kraft"],
["brought", "gebracht"],
["understand", "verstehen"],
["warm", "warm"],
["common", "häufig/üblich"],
["bring", "bringen"],
["explain", "erklären"],
["dry", "trocken"],
["though", "jedoch/obwohl"],
["language", "die Sprache"],
["shape", "die Form"],
["deep", "tief"],
["equation", "die Gleichung"],
["yet", "bisher/bislang"],
["government", "die Regierung"],
["filled", "gefüllt"],
["heat", "die Hitze"],
["full", "voll"],
["object", "das Objekt"],
["rule", "die Regel"],
["among", "zwischen/inmitten"],
["noun", "das Nomen"],
["power", "die Macht"],
["able", "fähig"],
["size", "die Größe"],
["dark", "dunkel"],
["material", "das Material"],
["special", "besonders"],
["heavy", "schwer"],
["pair", "das Paar"],
["circle", "der Kreis"],
["include", "einschließen/beinhalten"],
["built", "gebaut"],
["cross", "verärgert"],
["speak", "spreachen"],
["solve", "lösen"],
["appear", "erscheinen"],
["metal", "das Metall"],
["son", "der Sohn"],
["either", "entweder"],
["ice", "das Eis"],
["sleep", "schlafen"],
["village", "das Dorf"],
["result", "das Ergebnis"],
["jump", "springen"],
["snow", "der Schnee"],
["ride", "reiten/fahren"],
["care", "sich kümmern"],
["floor", "der Boden"],
["hill", "der Hügel"],
["push", "drücken/stoßen"],
["buy", "kaufen"],
["century", "Jahrhundert"],
["outside", "draußen"],
["everything", "alles"],
["tall", "groß/hoch"],
["already", "schon"],
["instead", "stattdessen"],
["phrase", "die Phrase/Formulierung"],
["soil", "der Boden"],
["bed", "das Bett"],
["copy", "kopieren"],
["free", "frei"],
["hope", "die Hoffung"],
["spring", "der Frühling"],
["case", "der Fall"],
["laugh", "lachen"],
["nation", "die Nation"],
["quite", "ziemlich"],
["type", "der Typ/Typus"],
["bright", "hell"],
["lead", "führen"],
["everyone", "jeder"],
["method", "die Methode"],
["section", "die Sektion"],
["lake", "der See"],
["within", "in/drinnen"],
["dictionary", "das Wörterbuch"],
["hair", "das Haar"],
["age", "das Alter"],
["amount", "die Menge"],
["scale", "das Ausmaß"],
["although", "obwohl"],
["broken", "gebrochen/zerstört"],
["moment", "der Moment"],
["tiny", "winzig"],
["possible", "möglich"],
["quiet", "ruhig"],
["natural", "natürlich"],
["stone", "Stein"],
["act", "handeln"],
["build", "bauen"],
["middle", "mitte"],
["speed", "die Geschwindigkeit"],
["count", "zählen"],
["someone", "einer"],
["sail", "segeln"],
["roll", "rollen"],
["bear", "der Bär"],
["wonder", "sich wundern"],
["smile", "lächeln"],
["angle", "der Winkel"],
["fraction", "der Bruchteil"],
["kill", "töten"],
["melody", "die Melodie"],
["trip", "die Reise"],
["hole", "das Loch"],
["poor", "arm"],
["let's", "lass uns"],
["fight", "kämpfen"],
["surprise", "die Überraschung"],
["die", "sterben"],
["exactly", "genau"],
["remain", "bleiben/verbleiben"],
["dress", "die Kleidung"],
["iron", "das Eisen"],
["finger", "der Finger"],
["row", "die Reihe"],
["least", "wenigstens"],
["catch", "fangen"],
["climb", "klettern/erklimmen"],
["write", "schreiben"],
["shout", "rufen/ausrufen"],
["continue", "fortsetzen"],
["gas", "das Gas"],
["burn", "brennen"],
["design", "Design"],
["join", "vereinigen/anschließen"],
["foot", "der Fuß"],
["law", "das Recht"],
["ears", "die Ohren"],
["grass", "das Graß"],
["grow", "wachsen"],
["skin", "die Haut"],
["valley", "das Tal"],
["key", "der Schlüssel"],
["president", "der Präsident"],
["brown", "braun"],
["trouble", "Schwierigkeit"],
["cloud", "die Wolke"],
["lost", "verloren"],
["sent", "gesendet"],
["symbol", "das Symbol"],
["wear", "tragen"],
["bad", "schlecht"],
["save", "speichern/sparen"],
["experiment", "das Experiment"],
["engine", "der Motor"],
["alone", "allein"],
["drawing", "die Zeichnung"],
["pay", "bezahlen"],
["signal", "das Signal"],
["touch", "berühren"],
["express", "ausdrücken"],
["mouth", "der Mund"],
["yard", "der Hof/der Garten"],
["equal", "gleich"],
["yourself", "du selbst"],
["control", "die Kontrolle"],
["practice", "die Übung"],
["report", "der Report"],
["straight", "gerade/direkt"],
["rise", "steigen/aufsteigen"],
["statement", "die Aussage/Angabe"],
["stick", "der Stock"],
["seeds", "das Saatgut"],
["suppose", "annehmen"],
["woman", "die Frau"],
["coast", "die Küste"],
["bank", "die Bank"],
["period", "die Periode"],
["wire", "das Kabel"],
["choose", "wählen"],
["clean", "sauber"],
["visit", "besuchen"],
["bit", "ein bisschen"],
["whose", "dessen"],
["received", "empfangen"],
["garden", "der Garten"],
["please", "bitte"],
["strange", "merkwürdig"],
["caught", "erwischt"],
["captain", "der Kapitän"],
["direct", "direkt"],
["ring", "der Ring"],
["serve", "dienen"],
["child", "das Kind"],
["desert", "die Wüste"],
["increase", "zunehmen/größer werden"],
["history", "die Geschichte"],
["cost", "die Kosten"],
["maybe", "vielleicht"],
["business", "das Geschäft"],
["separate", "getrennt"],
["break", "die Pause"],
["uncle", "der Onkel"],
["hunting", "jagen"],
["flow", "fließen"],
["lady", "die Lady"],
["students", "die Studenten"],
["human", "der Mensch"],
["art", "die Kunst"],
["feeling", "das Gefühl"]]

vocab_arrow.each do |eng, ger|
  Word.create(english: eng, german: ger)
end
